/**
 * TypeScript types mirroring the Claude Code settings.json schema.
 * Source: https://code.claude.com/docs/en/settings
 */

export interface PermissionSettings {
  allow?: string[];
  ask?: string[];
  deny?: string[];
  additionalDirectories?: string[];
  defaultMode?: string;
  disableBypassPermissionsMode?: 'disable' | string;
}

export interface SandboxNetworkSettings {
  allowUnixSockets?: string[];
  allowAllUnixSockets?: boolean;
  allowLocalBinding?: boolean;
  allowedDomains?: string[];
  httpProxyPort?: number | null;
  socksProxyPort?: number | null;
}

export interface SandboxSettings {
  enabled?: boolean;
  autoAllowBashIfSandboxed?: boolean;
  excludedCommands?: string[];
  allowUnsandboxedCommands?: boolean;
  network?: SandboxNetworkSettings;
  enableWeakerNestedSandbox?: boolean;
}

export interface McpServerRef {
  serverName: string;
}

export interface MarketplaceSource {
  source: string;
  repo: string;
}

export interface ClaudeCodeSettings {
  $schema?: string;
  permissions?: PermissionSettings;
  sandbox?: SandboxSettings;
  allowManagedPermissionRulesOnly?: boolean;
  allowManagedHooksOnly?: boolean;
  strictKnownMarketplaces?: MarketplaceSource[];
  allowedMcpServers?: McpServerRef[];
  deniedMcpServers?: McpServerRef[];
  enableAllProjectMcpServers?: boolean;
  // Not generated by any threat mitigation; included for schema completeness.
  enabledMcpjsonServers?: string[];
  disabledMcpjsonServers?: string[];
  disableAllHooks?: boolean;
  [key: string]: unknown;
}

export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends (infer U)[]
    ? U[]
    : T[P] extends object
      ? DeepPartial<T[P]>
      : T[P];
};

export type SettingsTarget = 'user' | 'project' | 'local' | 'managed';
